import { StyleSheet,Dimensions } from "react-native";

const BOARD_SIZE = 5;
const WINDOW_WIDTH = Dimensions.get('window').width;
const CELL_SIZE = Math.min(WINDOW_WIDTH / (BOARD_SIZE + 1), 70);
const CELL_MARGIN = 4;

 export const styles = StyleSheet.create({
 
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#776e65',
    marginBottom: 10,
  },
  gameInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 10,
  },
  scoreContainer: {
    backgroundColor: '#bbada0',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    minWidth: 80,
  },
  scoreLabel: {
    color: '#eee4da',
    fontSize: 14,
    fontWeight: 'bold',
  },
  scoreValue: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
  levelContainer: {
    backgroundColor: '#bbada0',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    minWidth: 100,
  },
  levelLabel: {
    color: '#eee4da',
    fontSize: 14,
    fontWeight: 'bold',
  },
  goalLabel: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  controls: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  button: {
    backgroundColor: '#8f7a66',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
    marginHorizontal: 10,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modeToggleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    backgroundColor: '#bbada0',
    padding: 8,
    borderRadius: 20,
  },
  modeText: {
    fontSize: 16,
    color: '#f9f6f2',
    marginRight: 10,
  },
  completionMessage: {
    position: 'absolute',
    bottom: 20,
    backgroundColor: 'rgba(121, 185, 60, 0.9)',
    padding: 10,
    borderRadius: 10,
    alignSelf: 'center',
  },
  completionText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  tutorialContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  tutorialContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    width: '80%',
    alignItems: 'center',
  },
  tutorialTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#776e65',
  },
  tutorialText: {
    fontSize: 16,
    color: '#776e65',
    marginBottom: 15,
    textAlign: 'center',
  },
  tutorialButton: {
    backgroundColor: '#8f7a66',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
  },
  tutorialButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  swipePathLine: {
    position: 'absolute',
    // backgroundColor: 'rgba(255, 255, 255, 0.5)',
    zIndex: 5,
  },
  gameOverContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(238, 228, 218, 0.73)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  gameOverMessage: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#776e65',
    marginBottom: 20,
  },
  gameWonMessage: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#f9f6f2',
    backgroundColor: '#EDC22E',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 20,
  },
   container: {
    flex: 1,
    backgroundColor: '#dsdsd',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    width: '100%',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  board: {
    width: (CELL_SIZE + CELL_MARGIN * 2) * BOARD_SIZE,
    height: (CELL_SIZE + CELL_MARGIN * 2) * BOARD_SIZE,
    backgroundColor: '#fffffc',
    borderRadius: 8,
    marginVertical: 30,
    marginHorizontal: 12,
  },
  row: {
    flexDirection: 'row',
  },
  cellContainer: {
    width: CELL_SIZE + CELL_MARGIN * 2,
    height: CELL_SIZE + CELL_MARGIN * 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cell: {
    width: CELL_SIZE,
    height: CELL_SIZE,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    margin: CELL_MARGIN,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cellText: {
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#FFF',
  },
  selectedCell: {
    borderWidth: 3,
    borderColor: '#FFF',
    shadowColor: '#FFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  // Animation related styles
  selectionBadge: {
    position: 'absolute',
    top: -10,
    right: -10,
    backgroundColor: '#FF4081',
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFF',
  },
  selectionBadgeText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  swipeModeText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 12,
  },
  swipePathContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
  },
  swipePath: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  // Additional styles for animations
  boardOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    zIndex: 20,
  },
  connectionLine: {
    position: 'absolute',
    zIndex: 5,
  },
  mergeEffect: {
    position: 'absolute',
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  shimmer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  validPatternIndicator: {
    position: 'absolute',
    bottom: 20,
    padding: 10,
    backgroundColor: '#4CAF50',
    borderRadius: 8,
    zIndex: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  validPatternText: {
    color: '#FFF',
    fontWeight: 'bold',
    marginLeft: 5,
  },
  backgroundPattern: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    zIndex: 10,
  },
  pauseButton: {
    marginTop: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },

}
);


 